export const regionList = [
  { id: 1, code: '11', name: '서울특별시' },
  { id: 2, code: '21', name: '부산광역시' },
  { id: 3, code: '22', name: '대구광역시' },
  { id: 4, code: '23', name: '인천광역시' },
  { id: 5, code: '24', name: '광주광역시' },
  { id: 6, code: '25', name: '대전광역시' },
  { id: 7, code: '26', name: '울산광역시' },
  { id: 8, code: '29', name: '세종특별자치시' },
  { id: 9, code: '31', name: '경기도' },
  { id: 10, code: '32', name: '강원특별자치도' },
  { id: 11, code: '33', name: '충청북도' },
  { id: 12, code: '34', name: '충청남도' },
  { id: 13, code: '35', name: '전북특별자치도' },
  { id: 14, code: '36', name: '전라남도' },
  { id: 15, code: '37', name: '경상북도' },
  { id: 16, code: '38', name: '경상남도' },
  { id: 17, code: '39', name: '제주특별자치도' }
];

export const dtlRegionList = [
  // --- 서울특별시 (11) ---
  { code: '11010', regionName: '서울특별시', dtlRegionName: '종로구' },
  { code: '11020', regionName: '서울특별시', dtlRegionName: '중구' },
  { code: '11030', regionName: '서울특별시', dtlRegionName: '용산구' },
  { code: '11040', regionName: '서울특별시', dtlRegionName: '성동구' },
  { code: '11050', regionName: '서울특별시', dtlRegionName: '광진구' },
  { code: '11060', regionName: '서울특별시', dtlRegionName: '동대문구' },
  { code: '11070', regionName: '서울특별시', dtlRegionName: '중랑구' },
  { code: '11080', regionName: '서울특별시', dtlRegionName: '성북구' },
  { code: '11090', regionName: '서울특별시', dtlRegionName: '강북구' },
  { code: '11100', regionName: '서울특별시', dtlRegionName: '도봉구' },
  { code: '11110', regionName: '서울특별시', dtlRegionName: '노원구' },
  { code: '11120', regionName: '서울특별시', dtlRegionName: '은평구' },
  { code: '11130', regionName: '서울특별시', dtlRegionName: '서대문구' },
  { code: '11140', regionName: '서울특별시', dtlRegionName: '마포구' },
  { code: '11150', regionName: '서울특별시', dtlRegionName: '양천구' },
  { code: '11160', regionName: '서울특별시', dtlRegionName: '강서구' },
  { code: '11170', regionName: '서울특별시', dtlRegionName: '구로구' },
  { code: '11180', regionName: '서울특별시', dtlRegionName: '금천구' },
  { code: '11190', regionName: '서울특별시', dtlRegionName: '영등포구' },
  { code: '11200', regionName: '서울특별시', dtlRegionName: '동작구' },
  { code: '11210', regionName: '서울특별시', dtlRegionName: '관악구' },
  { code: '11220', regionName: '서울특별시', dtlRegionName: '서초구' },
  { code: '11230', regionName: '서울특별시', dtlRegionName: '강남구' },
  { code: '11240', regionName: '서울특별시', dtlRegionName: '송파구' },
  { code: '11250', regionName: '서울특별시', dtlRegionName: '강동구' },

  // --- 부산광역시 (21) ---
  { code: '21010', regionName: '부산광역시', dtlRegionName: '중구' },
  { code: '21020', regionName: '부산광역시', dtlRegionName: '서구' },
  { code: '21030', regionName: '부산광역시', dtlRegionName: '동구' },
  { code: '21040', regionName: '부산광역시', dtlRegionName: '영도구' },
  { code: '21050', regionName: '부산광역시', dtlRegionName: '부산진구' },
  { code: '21060', regionName: '부산광역시', dtlRegionName: '동래구' },
  { code: '21070', regionName: '부산광역시', dtlRegionName: '남구' },
  { code: '21080', regionName: '부산광역시', dtlRegionName: '북구' },
  { code: '21090', regionName: '부산광역시', dtlRegionName: '해운대구' },
  { code: '21100', regionName: '부산광역시', dtlRegionName: '사하구' },
  { code: '21110', regionName: '부산광역시', dtlRegionName: '금정구' },
  { code: '21120', regionName: '부산광역시', dtlRegionName: '강서구' },
  { code: '21130', regionName: '부산광역시', dtlRegionName: '연제구' },
  { code: '21140', regionName: '부산광역시', dtlRegionName: '수영구' },
  { code: '21150', regionName: '부산광역시', dtlRegionName: '사상구' },
  { code: '21310', regionName: '부산광역시', dtlRegionName: '기장군' },

  // --- 대구광역시 (22) ---
  { code: '22010', regionName: '대구광역시', dtlRegionName: '중구' },
  { code: '22020', regionName: '대구광역시', dtlRegionName: '동구' },
  { code: '22030', regionName: '대구광역시', dtlRegionName: '서구' },
  { code: '22040', regionName: '대구광역시', dtlRegionName: '남구' },
  { code: '22050', regionName: '대구광역시', dtlRegionName: '북구' },
  { code: '22060', regionName: '대구광역시', dtlRegionName: '수성구' },
  { code: '22070', regionName: '대구광역시', dtlRegionName: '달서구' },
  { code: '22310', regionName: '대구광역시', dtlRegionName: '달성군' },

  // --- 인천광역시 (23) ---
  { code: '23010', regionName: '인천광역시', dtlRegionName: '중구' },
  { code: '23020', regionName: '인천광역시', dtlRegionName: '동구' },
  { code: '23030', regionName: '인천광역시', dtlRegionName: '남구' },
  { code: '23040', regionName: '인천광역시', dtlRegionName: '연수구' },
  { code: '23050', regionName: '인천광역시', dtlRegionName: '남동구' },
  { code: '23060', regionName: '인천광역시', dtlRegionName: '부평구' },
  { code: '23070', regionName: '인천광역시', dtlRegionName: '계양구' },
  { code: '23080', regionName: '인천광역시', dtlRegionName: '서구' },
  { code: '23310', regionName: '인천광역시', dtlRegionName: '강화군' },
  { code: '23320', regionName: '인천광역시', dtlRegionName: '옹진군' },

  // --- 광주광역시 (24) ---
  { code: '24010', regionName: '광주광역시', dtlRegionName: '동구' },
  { code: '24020', regionName: '광주광역시', dtlRegionName: '서구' },
  { code: '24030', regionName: '광주광역시', dtlRegionName: '남구' },
  { code: '24040', regionName: '광주광역시', dtlRegionName: '북구' },
  { code: '24050', regionName: '광주광역시', dtlRegionName: '광산구' },

  // --- 대전광역시 (25) ---
  { code: '25010', regionName: '대전광역시', dtlRegionName: '동구' },
  { code: '25020', regionName: '대전광역시', dtlRegionName: '중구' },
  { code: '25030', regionName: '대전광역시', dtlRegionName: '서구' },
  { code: '25040', regionName: '대전광역시', dtlRegionName: '유성구' },
  { code: '25050', regionName: '대전광역시', dtlRegionName: '대덕구' },

  // --- 울산광역시 (26) ---
  { code: '26010', regionName: '울산광역시', dtlRegionName: '중구' },
  { code: '26020', regionName: '울산광역시', dtlRegionName: '남구' },
  { code: '26030', regionName: '울산광역시', dtlRegionName: '동구' },
  { code: '26040', regionName: '울산광역시', dtlRegionName: '북구' },
  { code: '26310', regionName: '울산광역시', dtlRegionName: '울주군' },

  // --- 세종특별자치시 (29) ---
  { code: '29010', regionName: '세종특별자치시', dtlRegionName: '세종시' },

  // --- 경기도 (31) ---
  { code: '31010', regionName: '경기도', dtlRegionName: '수원시' },
  { code: '31011', regionName: '경기도', dtlRegionName: '수원시 장안구' },
  { code: '31012', regionName: '경기도', dtlRegionName: '수원시 권선구' },
  { code: '31013', regionName: '경기도', dtlRegionName: '수원시 팔달구' },
  { code: '31014', regionName: '경기도', dtlRegionName: '수원시 영통구' },
  { code: '31020', regionName: '경기도', dtlRegionName: '성남시' },
  { code: '31021', regionName: '경기도', dtlRegionName: '성남시 수정구' },
  { code: '31022', regionName: '경기도', dtlRegionName: '성남시 중원구' },
  { code: '31023', regionName: '경기도', dtlRegionName: '성남시 분당구' },
  { code: '31030', regionName: '경기도', dtlRegionName: '의정부시' },
  { code: '31040', regionName: '경기도', dtlRegionName: '안양시' },
  { code: '31041', regionName: '경기도', dtlRegionName: '안양시 만안구' },
  { code: '31042', regionName: '경기도', dtlRegionName: '안양시 동안구' },
  { code: '31050', regionName: '경기도', dtlRegionName: '부천시' },
  { code: '31060', regionName: '경기도', dtlRegionName: '광명시' },
  { code: '31070', regionName: '경기도', dtlRegionName: '평택시' },
  { code: '31080', regionName: '경기도', dtlRegionName: '동두천시' },
  { code: '31090', regionName: '경기도', dtlRegionName: '안산시' },
  { code: '31091', regionName: '경기도', dtlRegionName: '안산시 상록구' },
  { code: '31092', regionName: '경기도', dtlRegionName: '안산시 단원구' },
  { code: '31100', regionName: '경기도', dtlRegionName: '고양시' },
  { code: '31101', regionName: '경기도', dtlRegionName: '고양시 덕양구' },
  { code: '31103', regionName: '경기도', dtlRegionName: '고양시 일산동구' },
  { code: '31104', regionName: '경기도', dtlRegionName: '고양시 일산서구' },
  { code: '31110', regionName: '경기도', dtlRegionName: '과천시' },
  { code: '31120', regionName: '경기도', dtlRegionName: '구리시' },
  { code: '31130', regionName: '경기도', dtlRegionName: '남양주시' },
  { code: '31140', regionName: '경기도', dtlRegionName: '오산시' },
  { code: '31150', regionName: '경기도', dtlRegionName: '시흥시' },
  { code: '31160', regionName: '경기도', dtlRegionName: '군포시' },
  { code: '31170', regionName: '경기도', dtlRegionName: '의왕시' },
  { code: '31180', regionName: '경기도', dtlRegionName: '하남시' },
  { code: '31190', regionName: '경기도', dtlRegionName: '용인시' },
  { code: '31191', regionName: '경기도', dtlRegionName: '용인시 처인구' },
  { code: '31192', regionName: '경기도', dtlRegionName: '용인시 기흥구' },
  { code: '31193', regionName: '경기도', dtlRegionName: '용인시 수지구' },
  { code: '31200', regionName: '경기도', dtlRegionName: '파주시' },
  { code: '31210', regionName: '경기도', dtlRegionName: '이천시' },
  { code: '31220', regionName: '경기도', dtlRegionName: '안성시' },
  { code: '31230', regionName: '경기도', dtlRegionName: '김포시' },
  { code: '31240', regionName: '경기도', dtlRegionName: '화성시' },
  { code: '31250', regionName: '경기도', dtlRegionName: '광주시' },
  { code: '31260', regionName: '경기도', dtlRegionName: '양주시' },
  { code: '31270', regionName: '경기도', dtlRegionName: '포천시' },
  { code: '31280', regionName: '경기도', dtlRegionName: '여주시' },
  { code: '31350', regionName: '경기도', dtlRegionName: '연천군' },
  { code: '31370', regionName: '경기도', dtlRegionName: '가평군' },
  { code: '31380', regionName: '경기도', dtlRegionName: '양평군' },

  // --- 강원특별자치도 (32) ---
  { code: '32010', regionName: '강원특별자치도', dtlRegionName: '춘천시' },
  { code: '32020', regionName: '강원특별자치도', dtlRegionName: '원주시' },
  { code: '32030', regionName: '강원특별자치도', dtlRegionName: '강릉시' },
  { code: '32040', regionName: '강원특별자치도', dtlRegionName: '동해시' },
  { code: '32050', regionName: '강원특별자치도', dtlRegionName: '태백시' },
  { code: '32060', regionName: '강원특별자치도', dtlRegionName: '속초시' },
  { code: '32070', regionName: '강원특별자치도', dtlRegionName: '삼척시' },
  { code: '32310', regionName: '강원특별자치도', dtlRegionName: '홍천군' },
  { code: '32320', regionName: '강원특별자치도', dtlRegionName: '횡성군' },
  { code: '32330', regionName: '강원특별자치도', dtlRegionName: '영월군' },
  { code: '32340', regionName: '강원특별자치도', dtlRegionName: '평창군' },
  { code: '32350', regionName: '강원특별자치도', dtlRegionName: '정선군' },
  { code: '32360', regionName: '강원특별자치도', dtlRegionName: '철원군' },
  { code: '32370', regionName: '강원특별자치도', dtlRegionName: '화천군' },
  { code: '32380', regionName: '강원특별자치도', dtlRegionName: '양구군' },
  { code: '32390', regionName: '강원특별자치도', dtlRegionName: '인제군' },
  { code: '32400', regionName: '강원특별자치도', dtlRegionName: '고성군' },
  { code: '32410', regionName: '강원특별자치도', dtlRegionName: '양양군' },

  // --- 충청북도 (33) ---
  { code: '33020', regionName: '충청북도', dtlRegionName: '충주시' },
  { code: '33030', regionName: '충청북도', dtlRegionName: '제천시' },
  { code: '33040', regionName: '충청북도', dtlRegionName: '청주시' },
  { code: '33041', regionName: '충청북도', dtlRegionName: '청주시 상당구' },
  { code: '33042', regionName: '충청북도', dtlRegionName: '청주시 서원구' },
  { code: '33043', regionName: '충청북도', dtlRegionName: '청주시 흥덕구' },
  { code: '33044', regionName: '충청북도', dtlRegionName: '청주시 청원구' },
  { code: '33320', regionName: '충청북도', dtlRegionName: '보은군' },
  { code: '33330', regionName: '충청북도', dtlRegionName: '옥천군' },
  { code: '33340', regionName: '충청북도', dtlRegionName: '영동군' },
  { code: '33350', regionName: '충청북도', dtlRegionName: '진천군' },
  { code: '33360', regionName: '충청북도', dtlRegionName: '괴산군' },
  { code: '33370', regionName: '충청북도', dtlRegionName: '음성군' },
  { code: '33380', regionName: '충청북도', dtlRegionName: '단양군' },
  { code: '33390', regionName: '충청북도', dtlRegionName: '증평군' },

  // --- 충청남도 (34) ---
  { code: '34010', regionName: '충청남도', dtlRegionName: '천안시' },
  { code: '34011', regionName: '충청남도', dtlRegionName: '천안시 동남구' },
  { code: '34012', regionName: '충청남도', dtlRegionName: '천안시 서북구' },
  { code: '34020', regionName: '충청남도', dtlRegionName: '공주시' },
  { code: '34030', regionName: '충청남도', dtlRegionName: '보령시' },
  { code: '34040', regionName: '충청남도', dtlRegionName: '아산시' },
  { code: '34050', regionName: '충청남도', dtlRegionName: '서산시' },
  { code: '34060', regionName: '충청남도', dtlRegionName: '논산시' },
  { code: '34070', regionName: '충청남도', dtlRegionName: '계룡시' },
  { code: '34080', regionName: '충청남도', dtlRegionName: '당진시' },
  { code: '34310', regionName: '충청남도', dtlRegionName: '금산군' },
  { code: '34330', regionName: '충청남도', dtlRegionName: '부여군' },
  { code: '34340', regionName: '충청남도', dtlRegionName: '서천군' },
  { code: '34350', regionName: '충청남도', dtlRegionName: '청양군' },
  { code: '34360', regionName: '충청남도', dtlRegionName: '홍성군' },
  { code: '34370', regionName: '충청남도', dtlRegionName: '예산군' },
  { code: '34380', regionName: '충청남도', dtlRegionName: '태안군' },

  // --- 전북특별자치도 (35) ---
  { code: '35010', regionName: '전북특별자치도', dtlRegionName: '전주시' },
  { code: '35011', regionName: '전북특별자치도', dtlRegionName: '전주시 완산구' },
  { code: '35012', regionName: '전북특별자치도', dtlRegionName: '전주시 덕진구' },
  { code: '35020', regionName: '전북특별자치도', dtlRegionName: '군산시' },
  { code: '35030', regionName: '전북특별자치도', dtlRegionName: '익산시' },
  { code: '35040', regionName: '전북특별자치도', dtlRegionName: '정읍시' },
  { code: '35050', regionName: '전북특별자치도', dtlRegionName: '남원시' },
  { code: '35060', regionName: '전북특별자치도', dtlRegionName: '김제시' },
  { code: '35310', regionName: '전북특별자치도', dtlRegionName: '완주군' },
  { code: '35320', regionName: '전북특별자치도', dtlRegionName: '진안군' },
  { code: '35330', regionName: '전북특별자치도', dtlRegionName: '무주군' },
  { code: '35340', regionName: '전북특별자치도', dtlRegionName: '장수군' },
  { code: '35350', regionName: '전북특별자치도', dtlRegionName: '임실군' },
  { code: '35360', regionName: '전북특별자치도', dtlRegionName: '순창군' },
  { code: '35370', regionName: '전북특별자치도', dtlRegionName: '고창군' },
  { code: '35380', regionName: '전북특별자치도', dtlRegionName: '부안군' },

  // --- 전라남도 (36) ---
  { code: '36010', regionName: '전라남도', dtlRegionName: '목포시' },
  { code: '36020', regionName: '전라남도', dtlRegionName: '여수시' },
  { code: '36030', regionName: '전라남도', dtlRegionName: '순천시' },
  { code: '36040', regionName: '전라남도', dtlRegionName: '나주시' },
  { code: '36060', regionName: '전라남도', dtlRegionName: '광양시' },
  { code: '36310', regionName: '전라남도', dtlRegionName: '담양군' },
  { code: '36320', regionName: '전라남도', dtlRegionName: '곡성군' },
  { code: '36330', regionName: '전라남도', dtlRegionName: '구례군' },
  { code: '36350', regionName: '전라남도', dtlRegionName: '고흥군' },
  { code: '36360', regionName: '전라남도', dtlRegionName: '보성군' },
  { code: '36370', regionName: '전라남도', dtlRegionName: '화순군' },
  { code: '36380', regionName: '전라남도', dtlRegionName: '장흥군' },
  { code: '36390', regionName: '전라남도', dtlRegionName: '강진군' },
  { code: '36400', regionName: '전라남도', dtlRegionName: '해남군' },
  { code: '36410', regionName: '전라남도', dtlRegionName: '영암군' },
  { code: '36420', regionName: '전라남도', dtlRegionName: '무안군' },
  { code: '36430', regionName: '전라남도', dtlRegionName: '함평군' },
  { code: '36440', regionName: '전라남도', dtlRegionName: '영광군' },
  { code: '36450', regionName: '전라남도', dtlRegionName: '장성군' },
  { code: '36460', regionName: '전라남도', dtlRegionName: '완도군' },
  { code: '36470', regionName: '전라남도', dtlRegionName: '진도군' },
  { code: '36480', regionName: '전라남도', dtlRegionName: '신안군' },

  // --- 경상북도 (37) ---
  { code: '37010', regionName: '경상북도', dtlRegionName: '포항시' },
  { code: '37011', regionName: '경상북도', dtlRegionName: '포항시 남구' },
  { code: '37012', regionName: '경상북도', dtlRegionName: '포항시 북구' },
  { code: '37020', regionName: '경상북도', dtlRegionName: '경주시' },
  { code: '37030', regionName: '경상북도', dtlRegionName: '김천시' },
  { code: '37040', regionName: '경상북도', dtlRegionName: '안동시' },
  { code: '37050', regionName: '경상북도', dtlRegionName: '구미시' },
  { code: '37060', regionName: '경상북도', dtlRegionName: '영주시' },
  { code: '37070', regionName: '경상북도', dtlRegionName: '영천시' },
  { code: '37080', regionName: '경상북도', dtlRegionName: '상주시' },
  { code: '37090', regionName: '경상북도', dtlRegionName: '문경시' },
  { code: '37100', regionName: '경상북도', dtlRegionName: '경산시' },
  { code: '37310', regionName: '경상북도', dtlRegionName: '군위군' },
  { code: '37320', regionName: '경상북도', dtlRegionName: '의성군' },
  { code: '37330', regionName: '경상북도', dtlRegionName: '청송군' },
  { code: '37340', regionName: '경상북도', dtlRegionName: '영양군' },
  { code: '37350', regionName: '경상북도', dtlRegionName: '영덕군' },
  { code: '37360', regionName: '경상북도', dtlRegionName: '청도군' },
  { code: '37370', regionName: '경상북도', dtlRegionName: '고령군' },
  { code: '37380', regionName: '경상북도', dtlRegionName: '성주군' },
  { code: '37390', regionName: '경상북도', dtlRegionName: '칠곡군' },
  { code: '37400', regionName: '경상북도', dtlRegionName: '예천군' },
  { code: '37410', regionName: '경상북도', dtlRegionName: '봉화군' },
  { code: '37420', regionName: '경상북도', dtlRegionName: '울진군' },
  { code: '37430', regionName: '경상북도', dtlRegionName: '울릉군' },

  // --- 경상남도 (38) ---
  { code: '38030', regionName: '경상남도', dtlRegionName: '진주시' },
  { code: '38050', regionName: '경상남도', dtlRegionName: '통영시' },
  { code: '38060', regionName: '경상남도', dtlRegionName: '사천시' },
  { code: '38070', regionName: '경상남도', dtlRegionName: '김해시' },
  { code: '38080', regionName: '경상남도', dtlRegionName: '밀양시' },
  { code: '38090', regionName: '경상남도', dtlRegionName: '거제시' },
  { code: '38100', regionName: '경상남도', dtlRegionName: '양산시' },
  { code: '38110', regionName: '경상남도', dtlRegionName: '창원시' },
  { code: '38111', regionName: '경상남도', dtlRegionName: '창원시 의창구' },
  { code: '38112', regionName: '경상남도', dtlRegionName: '창원시 성산구' },
  { code: '38113', regionName: '경상남도', dtlRegionName: '창원시 마산합포구' },
  { code: '38114', regionName: '경상남도', dtlRegionName: '창원시 마산회원구' },
  { code: '38115', regionName: '경상남도', dtlRegionName: '창원시 진해구' },
  { code: '38310', regionName: '경상남도', dtlRegionName: '의령군' },
  { code: '38320', regionName: '경상남도', dtlRegionName: '함안군' },
  { code: '38330', regionName: '경상남도', dtlRegionName: '창녕군' },
  { code: '38340', regionName: '경상남도', dtlRegionName: '고성군' },
  { code: '38350', regionName: '경상남도', dtlRegionName: '남해군' },
  { code: '38360', regionName: '경상남도', dtlRegionName: '하동군' },
  { code: '38370', regionName: '경상남도', dtlRegionName: '산청군' },
  { code: '38380', regionName: '경상남도', dtlRegionName: '함양군' },
  { code: '38390', regionName: '경상남도', dtlRegionName: '거창군' },
  { code: '38400', regionName: '경상남도', dtlRegionName: '합천군' },

  // --- 제주특별자치도 (39) ---
  { code: '39010', regionName: '제주특별자치도', dtlRegionName: '제주시' },
  { code: '39020', regionName: '제주특별자치도', dtlRegionName: '서귀포시' }
];
